/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Latihan extends javax.swing.JFrame {

    /**
     * Creates new form Latihan
     */
    public Latihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        absen = new javax.swing.JLabel();
        kelas = new javax.swing.JLabel();
        jurusan = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        idabsen = new javax.swing.JTextField();
        idnama = new javax.swing.JTextField();
        idkelas = new javax.swing.JComboBox<>();
        idalamat = new javax.swing.JTextField();
        metarsu = new javax.swing.JButton();
        okarse = new javax.swing.JButton();
        rpl = new javax.swing.JRadioButton();
        tkj = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("BIODATA SISWA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 120, 30);

        nama.setText("NAMA");
        getContentPane().add(nama);
        nama.setBounds(30, 70, 80, 14);

        absen.setText("ABSEN");
        getContentPane().add(absen);
        absen.setBounds(30, 110, 80, 14);

        kelas.setText("KELAS");
        getContentPane().add(kelas);
        kelas.setBounds(30, 150, 70, 14);

        jurusan.setText("JURUSAN");
        getContentPane().add(jurusan);
        jurusan.setBounds(30, 190, 80, 14);

        alamat.setText("ALAMAT");
        getContentPane().add(alamat);
        alamat.setBounds(30, 230, 70, 20);
        getContentPane().add(idabsen);
        idabsen.setBounds(140, 100, 220, 30);

        idnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnamaActionPerformed(evt);
            }
        });
        getContentPane().add(idnama);
        idnama.setBounds(140, 60, 220, 30);

        idkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7", "X TKJ 1", "X TKJ 2", "X TKJ 3", "X TKJ 4", "X TKJ 5", "X TKJ 6" }));
        idkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idkelasActionPerformed(evt);
            }
        });
        getContentPane().add(idkelas);
        idkelas.setBounds(140, 140, 220, 30);
        getContentPane().add(idalamat);
        idalamat.setBounds(140, 220, 220, 30);

        metarsu.setText("EXIT");
        metarsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metarsuActionPerformed(evt);
            }
        });
        getContentPane().add(metarsu);
        metarsu.setBounds(300, 290, 90, 30);

        okarse.setText("SEND");
        okarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okarseActionPerformed(evt);
            }
        });
        getContentPane().add(okarse);
        okarse.setBounds(90, 290, 90, 30);

        buttonGroup1.add(rpl);
        rpl.setText("RPL");
        getContentPane().add(rpl);
        rpl.setBounds(150, 180, 70, 40);

        buttonGroup1.add(tkj);
        tkj.setText("TKJ");
        getContentPane().add(tkj);
        tkj.setBounds(270, 183, 93, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\ts2.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 0, 290, 430);

        setBounds(0, 0, 456, 473);
    }// </editor-fold>//GEN-END:initComponents

    private void idkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idkelasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idkelasActionPerformed

    private void metarsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metarsuActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_metarsuActionPerformed

    private void okarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okarseActionPerformed
        // TODO add your handling code here:
        String nama = idnama.getText();
        String absen = idabsen.getText();
        String kelas = idkelas.getSelectedItem().toString();
        String jurusan = "";
        String alamat = idalamat.getText();
        
        if (rpl.isSelected())
            jurusan ="RPL";
        else if (tkj.isSelected())
            jurusan ="TKJ";
        else
            
            if (idkelas.getSelectedItem()== "X RPL 1"){}
            if (idkelas.getSelectedItem()== "X RPL 2"){}
            if (idkelas.getSelectedItem()== "X RPL 3"){}
            if (idkelas.getSelectedItem()== "X RPL 4"){}
            if (idkelas.getSelectedItem()== "X RPL 5"){}
            if (idkelas.getSelectedItem()== "X RPL 6"){}
            if (idkelas.getSelectedItem()== "X RPL 7"){}
            if (idkelas.getSelectedItem()== "X TKJ 1"){}
            if (idkelas.getSelectedItem()== "X TKJ 2"){}
            if (idkelas.getSelectedItem()== "X TKJ 3"){}
            if (idkelas.getSelectedItem()== "X TKJ 4"){}
            if (idkelas.getSelectedItem()== "X TKJ 5"){}
            if (idkelas.getSelectedItem()== "X TKJ 6"){}
            
            new Hasil().setVisible(true);
        
            
    }//GEN-LAST:event_okarseActionPerformed

    private void idnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel absen;
    private javax.swing.JLabel alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idabsen;
    private javax.swing.JTextField idalamat;
    private javax.swing.JComboBox<String> idkelas;
    private javax.swing.JTextField idnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jurusan;
    private javax.swing.JLabel kelas;
    private javax.swing.JButton metarsu;
    private javax.swing.JLabel nama;
    private javax.swing.JButton okarse;
    private javax.swing.JRadioButton rpl;
    private javax.swing.JRadioButton tkj;
    // End of variables declaration//GEN-END:variables
}
